name: Deploy demo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        pip install datasette
    - name: Create databases
      run: |
        cat tests/squirrels.sql | sqlite3 squirrels.db
    - name: Set up Cloud Run
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '275.0.0'
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Deploy to Cloud Run
      run: |-
        gcloud config set run/region us-central1
        gcloud config set project datasette-222320
        datasette publish cloudrun penguins.db \
          --about=simonw/datasette-seaborn \
          --about_url=https://github.com/simonw/datasette-seaborn \
          --install=https://github.com/simonw/datasette-seaborn/archive/$GITHUB_SHA.zip \
          --service=datasette-seaborn \
          --title='datasette-seaborn demo'
